"""Alert Management Service.

Handles alert retrieval, status transitions, assignment, and statistics.
"""

import json
import logging
from datetime import datetime, timezone
from typing import Any

from sqlalchemy.orm import Session

from rules_engine.config import ALERT_PRIORITIES, ALERT_STATUSES
from rules_engine.database.models import Alert, AlertHistory

logger = logging.getLogger("garuda.rules.alerts")


class AlertService:
    """Service for managing alerts generated by intelligence rules."""

    @staticmethod
    def list_alerts(
        db: Session,
        project_id: str | None = None,
        rule_id: str | None = None,
        rule_type: str | None = None,
        priority: str | None = None,
        status: str | None = None,
        entity_id: str | None = None,
        assigned_to: str | None = None,
        mission_id: str | None = None,
        page: int = 0,
        page_size: int = 50,
    ) -> tuple[list[dict], int]:
        q = db.query(Alert)
        if project_id is not None:
            q = q.filter(Alert.project_id == project_id)
        if rule_id is not None:
            q = q.filter(Alert.rule_id == rule_id)
        if rule_type is not None:
            q = q.filter(Alert.rule_type == rule_type)
        if priority is not None:
            q = q.filter(Alert.priority == priority)
        if status is not None:
            q = q.filter(Alert.status == status)
        if entity_id is not None:
            q = q.filter(Alert.entity_id == entity_id)
        if assigned_to is not None:
            q = q.filter(Alert.assigned_to == assigned_to)
        if mission_id is not None:
            q = q.filter(Alert.mission_id == mission_id)

        total = q.count()
        items = q.order_by(Alert.created_at.desc()).offset(page * page_size).limit(page_size).all()
        return [a.to_dict() for a in items], total

    @staticmethod
    def get_alert(db: Session, alert_id: str) -> Alert | None:
        return db.query(Alert).filter(Alert.id == alert_id).first()

    @staticmethod
    def get_alert_with_history(db: Session, alert_id: str) -> dict:
        alert = db.query(Alert).filter(Alert.id == alert_id).first()
        if not alert:
            raise ValueError(f"Alert not found: {alert_id}")

        history = (
            db.query(AlertHistory)
            .filter(AlertHistory.alert_id == alert_id)
            .order_by(AlertHistory.created_at.asc())
            .all()
        )

        return {
            **alert.to_dict(),
            "history": [h.to_dict() for h in history],
        }

    @staticmethod
    def update_alert_status(
        db: Session,
        alert_id: str,
        status: str,
        actor: str | None = None,
        notes: str | None = None,
    ) -> Alert:
        if status not in ALERT_STATUSES:
            raise ValueError(f"Invalid alert status: {status}. Must be one of {ALERT_STATUSES}")

        alert = db.query(Alert).filter(Alert.id == alert_id).first()
        if not alert:
            raise ValueError(f"Alert not found: {alert_id}")

        previous_status = alert.status
        alert.status = status

        if status == "acknowledged":
            alert.acknowledged_at = datetime.now(timezone.utc)
        elif status == "resolved":
            alert.resolved_at = datetime.now(timezone.utc)

        ah = AlertHistory(
            alert_id=alert.id,
            action=status,
            actor=actor,
            notes=notes,
            previous_status=previous_status,
            new_status=status,
        )
        db.add(ah)
        db.commit()
        db.refresh(alert)

        logger.info(f"Alert {alert_id} status changed: {previous_status} -> {status}")
        return alert

    @staticmethod
    def assign_alert(
        db: Session,
        alert_id: str,
        assigned_to: str,
        actor: str | None = None,
    ) -> Alert:
        alert = db.query(Alert).filter(Alert.id == alert_id).first()
        if not alert:
            raise ValueError(f"Alert not found: {alert_id}")

        previous_assignee = alert.assigned_to
        alert.assigned_to = assigned_to

        ah = AlertHistory(
            alert_id=alert.id,
            action="assigned",
            actor=actor or assigned_to,
            notes=f"Assigned from {previous_assignee or 'unassigned'} to {assigned_to}",
            new_status=alert.status,
        )
        db.add(ah)
        db.commit()
        db.refresh(alert)

        logger.info(f"Alert {alert_id} assigned to {assigned_to}")
        return alert

    @staticmethod
    def acknowledge_alert(
        db: Session,
        alert_id: str,
        actor: str | None = None,
        notes: str | None = None,
    ) -> Alert:
        return AlertService.update_alert_status(db, alert_id, "acknowledged", actor, notes)

    @staticmethod
    def resolve_alert(
        db: Session,
        alert_id: str,
        actor: str | None = None,
        notes: str | None = None,
    ) -> Alert:
        return AlertService.update_alert_status(db, alert_id, "resolved", actor, notes)

    @staticmethod
    def get_alert_stats(
        db: Session,
        project_id: str | None = None,
    ) -> dict[str, Any]:
        q = db.query(Alert)
        if project_id is not None:
            q = q.filter(Alert.project_id == project_id)
        total = q.count()

        by_status = {}
        for s in ALERT_STATUSES:
            cnt = q.filter(Alert.status == s).count()
            if cnt > 0:
                by_status[s] = cnt

        by_priority = {}
        for p in ALERT_PRIORITIES:
            cnt = q.filter(Alert.priority == p).count()
            if cnt > 0:
                by_priority[p] = cnt

        by_rule_type = {}
        rt_query = db.query(Alert.rule_type, Alert.project_id) if project_id else db.query(Alert.rule_type)
        for row in q.with_entities(Alert.rule_type).distinct().all():
            rt = row[0]
            if rt:
                cnt = q.filter(Alert.rule_type == rt).count()
                by_rule_type[rt] = cnt

        recent = (
            q.order_by(Alert.created_at.desc()).limit(10).all()
        )

        return {
            "total_alerts": total,
            "by_status": by_status,
            "by_priority": by_priority,
            "by_rule_type": by_rule_type,
            "recent_alerts": [a.to_dict() for a in recent],
        }
